name: Test

on:
  pull_request:
  #push:
  #  branches: [ 'master' ]
  #  paths-ignore:
  #    - '.github/workflows/**'
  #    - 'README.md'

permissions:
  contents: read

jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        command: [
            "--forge --version 1.6.4-9.11.1.964",
            "--forge --version 1.7.10-10.13.4.1614-1.7.10",
            "--forge --version 1.8.9-11.15.1.2318-1.8.9",
            "--forge --version 1.12.2-14.23.5.2864",
            "--forge --version 1.20.1-47.4.0",
            "--forge --version 1.21.11-61.1.0",
            "--forge --version 26.1-62.0.0",
            "--client --version 1.20.1",
            "--server --version 1.20.1",
            "--mc --version 1.20.1",
            "--client --version 26.1-snapshot-1",
            "--server --version 26.1-snapshot-1"
        ]
        
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Test Run
        run: ./gradlew run --args="--debug ${{ matrix.command }}"